### ISSUE TITLE
regarding the know-evolve paper 

### ISSUE THREAD

**Issue by alisadeghian** [woojeongjin/dynamic-KG#1]
I would like to bring to your attention that the know-evolve paper has serious issues concerning their numerical results. IMHO it should not be advertised as a temporal link prediction paper. It would be great if you remove it or add a note next to it so it does not set an unreasonably high bar and discourage others from working on this benchmarks. 

P.S. please refer to https://github.com/rstriv/Know-Evolve/issues for more details. As another user also mentions with full details in the issues, the know-evolve model is saturated and all hits@10 calculations might be erroneous.

![image](https://user-images.githubusercontent.com/2513126/52810115-d419d580-305f-11e9-8033-9406d3656a8a.png)

**Comment by woojeongjin** [comment]
Yes, I am aware of it.
The author is going to fix the problem. 
Until then, I will temporarily remove it.
